iterations: 30000
densify_from_iter: 500
densify_until_iter: 15000
densification_interval: 100
opacity_reset_interval: 3000
position_lr_max_steps: 30000
position_lr_final: 0.0000016
position_lr_init: 0.00016
scaling_lr: 0.005
sh_degree: 3

uncertainty_warmup_start: 35000
uncertainty_warmup_iters: 5000
uncertainty_protected_iters: 2500
uncertainty_regularizer_weight: 0.5
uncertainty_mode: "disabled"
uncertainty_preserve_sky: false

appearance_enabled: false
appearance_n_fourier_freqs: 4

num_sky_gaussians: 0
