iterations: 70000
densify_from_iter: 1000
densify_until_iter: 52000
densification_interval: 400
opacity_reset_interval: 15000
position_lr_max_steps: 200000
position_lr_final: 0.00000016
position_lr_init: 0.000016
scaling_lr: 0.0005
sh_degree: 3

uncertainty_warmup_start: 17000
uncertainty_warmup_iters: 5000
uncertainty_protected_iters: 2500 #No uncertainty training right after opacity resets
uncertainty_regularizer_weight: 0.5
uncertainty_mode: "dino"
uncertainty_preserve_sky: false

appearance_enabled: false
appearance_n_fourier_freqs: 4

num_sky_gaussians: 0

